"""empty message

Revision ID: 036b4cfa6dc9
Revises: 9cc3e19635b6
Create Date: 2021-06-20 22:22:16.853247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036b4cfa6dc9'
down_revision = '9cc3e19635b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('user_surname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_surname_key', 'user', ['surname'])
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
