"""empty message

Revision ID: 1b19077a2c48
Revises: 1278aff5a955
Create Date: 2021-06-18 17:59:52.032984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b19077a2c48'
down_revision = '1278aff5a955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('user_surname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_surname_key', 'user', ['surname'])
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
