"""empty message

Revision ID: 28ff064b47e4
Revises: 1b19077a2c48
Create Date: 2021-06-23 15:56:02.731403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ff064b47e4'
down_revision = '1b19077a2c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('disease_user_id_fkey', 'disease', type_='foreignkey')
    op.drop_column('disease', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('disease_user_id_fkey', 'disease', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
